### ISSUE TITLE
Call to a member function addMembers() on null

### ISSUE THREAD

**Issue by codingspider** [musonza/groups#13]
Hello Support,
Hope your are doing well, I am new in laravel,  today i have installed your package in my laravel app. But when i am going to add member its saying Call to a member function addMembers() on null. please help me with this issue. 

Thanks

**Comment by musonza** [comment]
Can you show me some of the code? It means you are trying to add members to a group that doesn't exist

**Comment by codingspider** [comment]
public function add_member(){
   	$userId = 1;

   	$group->addMembers([$userId]);

   	return "ok";
   }

**Comment by musonza** [comment]
Where did you create the Group `$group`?

**Comment by codingspider** [comment]
public function index(){

   			$userId = 1;

		   	$data = [
		  'name'              => 'test',
		  'description'       => 'test description', // optional
		  'short_description' => 'test short description', // optional
		  'image'             => '', // optional
		  'private'           => 0,  // 0 (public) or 1 (private)
		  'extra_info'        => 'test info', // optional
		  'settings'          => '', // optional
		  'conversation_id'   => 0,  // optional if you want to add messaging to your groups this can be useful
		];

   			$group = Groups::create($userId, $data);

   			return "ok";
   }

   public function add_member(){
   	$userId = 1;

   	$group->addMembers([$userId]);

   	return "ok";
   }

**Comment by musonza** [comment]
Your `add_member` function doesn't know anything about which group you are referring to though since you are in a different function so you need to query for the group first before adding members. 

To learn more about Laravel you can watch https://laracasts.com/series/laravel-from-scratch-2018
