### ISSUE TITLE
add member to a group 

### ISSUE THREAD

**Issue by codingspider** [musonza/groups#14]
Hello sir, 

I am trying from yesterday to add member but I could not understand your functionality. can you please write the code for adding member into a group. Please sir this package is very important for my project. I am waiting for your kind response. 

Thanks

**Comment by musonza** [comment]
Take a look at this code
https://github.com/musonza/groups/blob/9bde27d614e53d1b16ade6339cd9a6f6a47ef82b/tests/GroupsTest.php#L59-L68
