### ISSUE TITLE
Groups table migration 

### ISSUE THREAD

**Issue by mehdithemaker** [musonza/groups#15]
Any solution for that problem please?
Migrating: 2019_05_26_125854_create_groups_tables

[   Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1005 Can't create table `groupsystem`.`#sql-2678_21` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `groups` add constraint `groups_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade)
](url)

**Comment by oliuz** [comment]
what version are you using?

**Comment by markoman78** [comment]
I'm using 5.8 and this fixed for me.

I changed all user_id integers which are pointed as foreign keys to unsignedBigIntegers. All other columns which are pointed as foreign keys to unsignedIntegers.

**Comment by mehdithemaker** [comment]
I changed the types to increments and it's working fine thank you for the
great work

**Comment by musonza** [comment]
https://github.com/musonza/groups/releases/tag/v1.2.0
