### ISSUE TITLE
Foreign Key problem with migrations

### ISSUE THREAD

**Issue by azcoppen** [musonza/groups#2]
When running php artisan migrate:

[Illuminate\Database\QueryException]                                                                                                                                                    
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `group_request` add constraint `group_request_group_id_foreign` foreign key (`group_id`) refe  
  rences `groups` (`id`) on delete cascade)

**Comment by musonza** [comment]
Did you create any of the tables manually? What was your process?

**Comment by azcoppen** [comment]
@musonza Followed instructions to the letter. Just ran migrate once the service provider was in, and after publish. Fix was to remove the constraints in the migrations.

**Comment by musonza** [comment]
@azcoppen feel free to make an update and I will accept the pull request. Thanks
