### ISSUE TITLE
does this work for creating groups with any model? or only with users?

### ISSUE THREAD

**Issue by vesper8** [musonza/groups#6]
I'd like to use this package to create groups of other models.. not users

**Comment by musonza** [comment]
Hi, works with users only. However, if you don't mind to explain your use case I can look at doing that for next version since an update is due or I can search for other packages that might have what you need.

**Comment by vesper8** [comment]
Well I simply wanted to create groups.. or collections.. for any model

So for example I have users and posts.. and I want users to be able to create lists and add their posts, or any user's posts.. to those lists. Similar to how Twitter let's you use lists

But I found a package that does exactly this.. still it would be nice for you to add it to your package as well. The one I found that does exactly what I wanted is https://github.com/faustbrian/Laravel-Collectable

**Comment by akwetey** [comment]
@musonza could you be kind enough to provide tutorial on how to use this package. my organization has this crowdfunding platform and we want to be able to allow users to create groups and be able to accept and decline request among other things. But currently we are facing difficulties implementing your package on our platform. After running the migrations we are currently lost on what to do next. I would love it if you could provide tutorial on how to implement your package. Thanks.

**Comment by musonza** [comment]
Did you look at the readme first? It has example usage. Also I haven’t checked if there are issues with new versions of laravel so I may need to update the package.

**Comment by akwetey** [comment]
@musonza  i did read the readme. so maybe what i was looking for is a demo. i'm new to laravel and your readme is not that very easy for newbies like me who wants to implement your package after running the installation. Maybe if we could get demo on how to use the package to create a project it would be very great. Thanks

**Comment by musonza** [comment]
Unfortunately i don't have time at the moment to create a demo. I would suggest looking at Laravel tutorials first before trying to implement.
